name: pkuapp
description: "PKU App powered by AI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  # google_sign_in: ^6.3.0
  http: ^1.2.1
  flutter_localizations:
    sdk: flutter
  intl: any
  pdf: ^3.10.8
  path_provider: ^2.1.3
  open_file_plus: ^3.4.1
  share_plus: ^9.0.0
  image_picker: ^1.1.2
  mobile_scanner: ^5.1.1
  flutter_markdown: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - .env